### ISSUE TITLE
Minor: TestAuthHandler shouldn't be in RestApi and instead in a test project

### ISSUE THREAD

**Issue by nosyrbllewe** [2011-fakebook-project3/posts#118]
The RestApi project has the TestAuthHandler. Test classes should instead be in a test project.

**Comment by 308butterfly** [comment]
Moved TestAuthHandler.cs into Fakebook.Posts/Fakebook.Posts.IntegrationTests/Services and changed the namespace to Fakebook.Posts.IntegrationTests.Services.

Pull request was approved by trainer
