### ISSUE TITLE
Critical: Posting too much information in /api/posts

### ISSUE THREAD

**Issue by nosyrbllewe** [2011-fakebook-project3/posts#122]
The endpoint /api/posts/ exposes way too much information when posting. The client should only post the content and the picture id, which is then validated by a DTO.

**Comment by ColeSamuelsen23** [comment]
Similarly with commenting, this issue is resolved with the DTOs that were implemented.  Clients can now only post the content of a post, and there are also certain restrictions on the size of the post they can make
